name: "Docker Image Publishing"

inputs:
  registry_username:
    description: "Username of Docker"
    required: true
  registry_password: 
    description: "Password for Docker"
    required: true
  image_name:
    description: "Name of the image"
    required: true
  tag:
    description: "Tag for the image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup BuildX
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}

    - name: Build and push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{inputs.registry_username}}/${{inputs.image_name}}:${{inputs.tag}}
